# Generated by Django 4.2.1 on 2023-05-24 22:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("celebrity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("imdb_id", models.CharField(blank=True, null=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("year", models.CharField(blank=True, max_length=255, null=True)),
                ("rating", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "certificate",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("duration", models.CharField(blank=True, max_length=255, null=True)),
                ("genre", models.CharField(blank=True, max_length=255, null=True)),
                ("votes", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "gross_income",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "director_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "director_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("starts_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "starts_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("ERROR", "Error"),
                            ("EXPIRED", "Expired"),
                            ("FORWARDED", "Forwarded"),
                        ],
                        default="READY",
                        max_length=50,
                    ),
                ),
                ("attempt", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
                "db_table": "movie",
                "ordering": ["-created", "-updated"],
            },
        ),
        migrations.CreateModel(
            name="MovieActor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="celebrity.actor",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="movies.movie"
                    ),
                ),
            ],
            options={
                "verbose_name": "Movie Actor",
                "verbose_name_plural": "Movies Actors",
                "db_table": "movie_actor",
                "ordering": ["-created", "-updated"],
            },
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["name"], name="M_name_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["description"], name="M_description_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["starts_name"], name="M_starts_name_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["status"], name="M_status_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["created"], name="M_created_idx"),
        ),
        migrations.AddIndex(
            model_name="movieactor",
            index=models.Index(fields=["created"], name="MA_created_idx"),
        ),
    ]
