# Generated by Django 4.2.1 on 2023-05-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_movie_description_alter_movie_payload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="starts_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
