# Generated by Django 4.2.1 on 2023-05-25 00:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_alter_movie_certificate_alter_movie_director_id_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="movie",
            name="M_name_idx",
        ),
        migrations.RemoveIndex(
            model_name="movie",
            name="M_description_idx",
        ),
        migrations.RemoveIndex(
            model_name="movie",
            name="M_starts_name_idx",
        ),
    ]
