# Generated by Django 4.2.1 on 2023-05-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_alter_movie_name_movie_m_name_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["imdb_id"], name="M_imdb_id_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["status", "attempt"], name="M_status_attempt_idx"
            ),
        ),
    ]
