# Generated by Django 4.2.1 on 2023-06-15 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("celebrity", "0011_alter_actorimage_actor"),
        ("movies", "0008_alter_movieactor_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieactor",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="celebrity.actor"
            ),
        ),
    ]
