# Generated by Django 4.2.1 on 2023-05-24 22:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("ERROR", "Error"),
                            ("EXPIRED", "Expired"),
                            ("FORWARDED", "Forwarded"),
                        ],
                        default="READY",
                        max_length=50,
                    ),
                ),
                ("attempt", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Actor",
                "verbose_name_plural": "Actors",
                "db_table": "actor",
                "ordering": ["-created", "-updated"],
            },
        ),
        migrations.CreateModel(
            name="ActorImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        choices=[
                            (" face", "Face"),
                            (" side face", "Side Face"),
                            (" looking up", "Looking Up"),
                            (" looking down", "Looking Down"),
                            (" wearning glasses", "Wearing Glasses"),
                            (" happy face", "Happy Face"),
                            (" nose", "Nose"),
                            (" close up", "Close Up"),
                        ],
                        max_length=50,
                    ),
                ),
                ("url", models.URLField()),
                ("path", models.FilePathField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("ERROR", "Error"),
                            ("EXPIRED", "Expired"),
                            ("FORWARDED", "Forwarded"),
                        ],
                        default="READY",
                        max_length=50,
                    ),
                ),
                ("attempt", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="celebrity.actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actor image",
                "verbose_name_plural": "Actors Images",
                "db_table": "actor_image",
                "ordering": ["-created", "-updated"],
            },
        ),
        migrations.AddIndex(
            model_name="actor",
            index=models.Index(fields=["name"], name="A_name_idx"),
        ),
        migrations.AddIndex(
            model_name="actor",
            index=models.Index(fields=["status"], name="A_status_idx"),
        ),
        migrations.AddIndex(
            model_name="actor",
            index=models.Index(fields=["created"], name="A_created_idx"),
        ),
        migrations.AddIndex(
            model_name="actorimage",
            index=models.Index(fields=["keyword"], name="AI_keyword_idx"),
        ),
        migrations.AddIndex(
            model_name="actorimage",
            index=models.Index(fields=["url"], name="AI_url_idx"),
        ),
        migrations.AddIndex(
            model_name="actorimage",
            index=models.Index(fields=["created"], name="AI_created_idx"),
        ),
    ]
