# Generated by Django 4.2.1 on 2023-05-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("celebrity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actorimage",
            name="path",
            field=models.TextField(blank=True, null=True),
        ),
    ]
