# Generated by Django 4.2.1 on 2023-05-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("celebrity", "0003_actor_birthday_actor_gender_actor_nationality"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actor",
            old_name="gender",
            new_name="imdb_id",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="nationality",
        ),
        migrations.AlterField(
            model_name="actorimage",
            name="keyword",
            field=models.CharField(
                choices=[
                    ("face young", "Face Young"),
                    (" face", "Face"),
                    (" side face", "Side Face"),
                    (" looking up", "Looking Up"),
                    (" looking down", "Looking Down"),
                    (" wearning glasses", "Wearing Glasses"),
                    (" happy face", "Happy Face"),
                    (" nose", "Nose"),
                    (" close up", "Close Up"),
                ],
                max_length=50,
            ),
        ),
    ]
