# Generated by Django 4.2.1 on 2023-05-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "celebrity",
            "0004_rename_gender_actor_imdb_id_remove_actor_nationality_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
