# Generated by Django 4.2.1 on 2023-05-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("celebrity", "0005_alter_actor_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="slug",
            field=models.SlugField(),
        ),
    ]
