# Generated by Django 4.2.1 on 2023-06-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("celebrity", "0006_alter_actor_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="actorimage",
            name="is_valid",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
