# Generated by Django 4.2.1 on 2023-06-15 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("celebrity", "0009_elasticsearchactorimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elasticsearchactorimage",
            name="actor_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="celebrity.actorimage"
            ),
        ),
    ]
